@startuml GestorClientes

class Cliente {
    -nombre
    -apellidos
    -dni
}

class GestorClientes {
    -clientes
    +buscarCliente(dni)
    +insertarCliente(cliente)
    +eliminarCliente(dni)
    +modificarCliente(cliente)
}

Cliente <|-- GestorClientes

@enduml
